server:
  port: ${SERVER_PORT:8102}
  shutdown: graceful

keycloak:
  enabled: true
  realm: bank
  auth-server-url: http://localhost:8200/auth/
  resource: gate-service-app
  public-client: true
  bearer-only: false

logging:
  level:
    root: INFO
    org:
      keycloak:
        adapters: ERROR