version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $KEYCLOAK_DB
      POSTGRES_USER: $KEYCLOAK_DB_USER
      POSTGRES_PASSWORD: $KEYCLOAK_DB_PASSWORD
      
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - 8200:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: $KEYCLOAK_DB
      DB_SCHEMA: $KEYCLOAK_DB_SCHEMA
      DB_USER: $KEYCLOAK_DB_USER
      DB_PASSWORD: $KEYCLOAK_DB_PASSWORD
      KEYCLOAK_USER: $KEYCLOAK_USER
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
    depends_on:
      - postgres
    links:
      - postgres:postgres    

volumes:
  postgres_data:
    driver: local